version: "3.3"

services:
  server:
    build:
      context: docker/nginx
    volumes:
      - ./wordpress:/app
      #- ./nginx-conf:/etc/nginx/conf.d
      #- certbot-etc:/etc/letsencrypt
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./wordpress:/app

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./wordpress:/app

  database:
    build:
      context: docker/mariadb
    volumes:
      - ./docker/databases/mariadb:/var/lib/mariadb
    environment:
      - MYSQL_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"

  phpadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      - PMA_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=3306
    ports:
      - "8000:80"

#  certbot:
#    depends_on:
#      - webserver
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - certbot-etc:/etc/letsencrypt
#      - wordpress:/var/www/html
#    command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com -d www.example.com